default:
  target: "{{ env_var('PROFILE_TARGET') }}"
  outputs:

    snowflake_prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_HOST') }}"

      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: public
      threads: 1

